name: "Clean up github artifacts (weekly)"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 6" # every saturday at6 am UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 7days
